### ISSUE TITLE
Use GitHub commit activity as part of calculation

### ISSUE THREAD

**Issue by eddiejaoude** [mnapoli/IsItMaintained#21]
Issues open/close metric alone isn't enough, GitHub commit activity should be include and weight more in my opinion.

**Comment by wdmtech** [comment]
:+1:

**Comment by carbontwelve** [comment]
I agree, at current a project that had a good response time can still have had no commit activity for months/years and be considered well maintained if nobody has raised any more issues in the interim.

**Comment by tentacode** [comment]
Commit activity is not in any way a good sign that a project is maintained, it's a sign that it's active, and sometime it could be active for the wrong reason, just pushing bad code, not fixing issue. This metric is irrelevant IMOH.

**Comment by eddiejaoude** [comment]
Individually most metrics are irrelevant. Its the combination & weighting of multiple metrics that give the value add. This is a good start, but I would want a few more metrics to give a fair weighting on the result.

**Comment by mnapoli** [comment]
Like @tentacode said I am also :-1: on this idea. There was a similar discussion here: https://github.com/mnapoli/IsItMaintained/issues/13#issuecomment-56919479

In short, some projets are stable. They don't have new commits or new releases because they don't need any. And it doesn't mean they are not maintained.

Finding out the activity of a project is simple, and GitHub does that well. What's interesting to know and not obvious on GitHub (i.e. the whole point of this project), is how well is the project *maintained*, i.e. "are bugs handled and closed fast?" And I think the current metrics (even though they could be improved: #12) work.

A way to prove this is the current metrics push developers to fix bugs faster (i.e. close issues labelled as "bugs" faster). If we added commit activity, it would only push developers to commit more often -> what's the point? What do users gain with that?

I think a "whole in one" and "perfect" indicator is out of reach (only a human could do it), so I'd rather fallback on meaningful metrics rather than do a random sum of unrelated metrics in the hopes of obtaining something meaningful as a result.

**Comment by eddiejaoude** [comment]
Fair point, however if someone is using the Issue part of GitHub for their **Backlog** / Ideas etc, then they will have items in there for many months - this will appear as a badly maintained project yet it is actually well maintained because it has a roadmap of where it would like to go.

**Comment by mnapoli** [comment]
@eddiejaoude that's why there's a wide list of issue exclusions based on labels. It works for most of the big projects I've tested this app with. But obviously projects not categorizing their issues (i.e. separating bugs and features) won't have a meaningful indicator.

**Comment by eddiejaoude** [comment]
> wide list of issue exclusions based on labels

Ah ok. I wasn't aware of that.

> projects not categorizing their issues

Then its their fault, if the functionality exists to exclude backlog type items

**Comment by mourner** [comment]
I agree that this is a meaningless metric. I have many small and focused JS libraries that have no recent commit activity because they don't need new features and are so stable that there are no knows issues left to fix.

**Comment by eddiejaoude** [comment]
> don't need new features and are so stable

Really @mourner ? Surely, no project is ever perfect or ever finished ... just my experience, but GitHub wouldn't be so active and wonderful :wink:

**Comment by mourner** [comment]
@eddiejaoude a lot of my libraries are computational geometry algorithms. They don't change often.

**Comment by mnapoli** [comment]
@eddiejaoude Check out this library for example: https://github.com/myclabs/php-enum 200k downloads, used everyday by plenty of projects yet only 57 commits, and the project is maintained. It's an enum library, it doesn't changes every day.

**Comment by eddiejaoude** [comment]
Thanks, its a good example. I am not trying to say it will change every day, but there will still be future commits, as I am sure there can be improvements/new features added. I agree maybe it is not a great metric, but it does have a small influence. Just like code coverage is not a great metric, but it is a metric nonetheless that does give feedback. 

Google uses lots of metrics each has different weighting, I don't think a single metric no matter how good can do it alone. Having more with different / small influences would provide more valid add. Just my 2 cents.

May be we will agree to just disagree on this one :smile:
